### ISSUE TITLE
Print Screen key shortcut 

### ISSUE THREAD

**Issue by Healarybuf** [XMuli/SunnyPages#2]
Hey great software, thanks for making it.

Would it be possible to allow us to bind hotkey to "Print Screen"? The goal would be to replace Snipping tool. I know it's possible because Greenshot does it!

**Comment by XMuli** [comment]
Thanks for your feedback, I'll try to fix it and support `PrtScn` keyboard button binding!

**Comment by XMuli** [comment]
This bug is not as easy as I thought it would be; but I'll try other solutions for it later on

**Comment by XMuli** [comment]
Hi friends; Print Screen key cannot be detected has been fixed in the [v2.2.1](https://github.com/XMuli/SunnyPages/releases/tag/v2.2.1) version;

However, this key is a system specific key that prioritizes the response to normal keys; and it's not the same for windows 10 and windows 11, in the latter it's the default shortcut for screenshots, which needs to be turned off in the settings of win11 - and make sure that this shortcut is not registered by other software, then it can be responded to; perhaps it's more recommended to use F1 as the capture key.

And make sure that this shortcut is not registered by other software, so it can be responded to; perhaps it is more recommended to use F1 as a capture key (a habit).

<img src="https://github.com/user-attachments/assets/8713c016-1efb-4c3d-bf7b-27a93c30d176" width="70%"/>

**Comment by XMuli** [comment]
Done
