### ISSUE TITLE
serial numbers don't work

### ISSUE THREAD

**Issue by thiagodalsoto** [XMuli/SunnyPages#35]
The function to insert serial numbers, available in the toolbar, is not working in Linux Ubuntu 24.04, I tested it in Windows 11 and it works, I remember having tested this feature previously in Linux and it was 100% functional, I don't know if this has changed in the last few years versions, or was it some shared lib that is causing the problem.

Below is an image to illustrate the problem
![Erro Numbers](https://github.com/XMuli/SunnyPages/assets/30872231/62c0f14e-8d20-482a-a956-f5d8921c98f1)

**Comment by XMuli** [comment]
Thanks for your feedback, I will debug linux for this reason.
Guess it could be that some variable in linux forgot to assign a value?

If you know C++/Qt, I'd be happy to send you a copy of the source code!

**Comment by thiagodalsoto** [comment]
Good morning...

Unfortunately, looking at the code I wouldn't be able to add anything, I don't have any developer knowledge, I'm just an enthusiast in using it :)
But I found something here that should help you find the problem, as I said I had already tested the feature and it was functional, I started installing the old versions, in 1.6.2 the problem also occurs, but in version 1.5 it works, that's it. It should eliminate what I thought could be some OS lib that caused the problem, I believe that now it is more related to the code itself.

If you encounter the problem, and need help testing, just send me the .deb before publishing and I will be happy to help.

![Serial](https://github.com/XMuli/SunnyPages/assets/30872231/693e0cfa-8d26-456d-9a69-5bd82f5af7b1)

**Comment by XMuli** [comment]
ok, good evening 🤓🤓

**Comment by XMuli** [comment]
Hi, @thiagodalsoto  and @Creling

Fixed in new version [v2.2.1](https://github.com/XMuli/SunnyPages/releases/tag/v2.2.1) released last night;
And the serial number tag works perfectly in Ubuntu22.04 / Deepin23 / Debian12.5 / Win 10, 11!

**Linux:**
<img src="https://github.com/user-attachments/assets/3657c0e9-0359-4146-819d-af1e364d26ef" width="70%"/>

**Windows:**
<img src="https://github.com/user-attachments/assets/d24114d8-5298-4401-a866-a42c65558aa7" width="70%"/>

**Comment by thiagodalsoto** [comment]
checked, working... congratulations
